Create websocket message architecture
hebitigo/CATechAccelChatApp pull request #6
Opened 2024-01-25 12:44 UTC by hebitigo

/ws/joinChannel/:server_Id/:channel_Id/:user_Id
POST /registerServer
POST /registerUser
のエンドポイントを作りました。

/ws/joinChannel/:server_Id/:channel_Id/:user_Id
の実装はwsに切り出してます。メッセージがwebsocketのconnection経由で送られた際にMessagesテーブルを更新するための処理はrepositoryに書いてuserで呼び出しています

2024-01-25 15:31 UTC, kei01234kei commented on handler/handler.go
> +		return
error の書式指定子には多くの情報を表示できるように `%+v` を使うとよさそう。
参照: https://pkg.go.dev/fmt

```go
// fmt.Sprintf("botEndpointParams validation failed:%s", err.Error())
fmt.Sprintf("botEndpointParams validation failed: %+v", err)
```

2024-01-25 15:36 UTC, kei01234kei commented on handler/handler.go
> +	}
個人的な好みの話になるけど、ぼくは err 変数にエラーを代入する部分と if のエラーハンドリングは分ける方が好きかも。
分けた方がコードの可読性が高くなる気がするから。

```go
	err := validator.Struct(request)
	if err != nil {
		c.JSON(400, gin.H{"error": fmt.Sprintf("request validation failed:%s", err.Error())})
		return
	}
```

2024-01-25 15:38 UTC, kei01234kei commented on repository/repository.go
> +}
fmt.Println じゃなくて log.Println を使うようにしよう。
あと、エラー処理をしてからログを吐くようにしよう！

```go
	_, err := repo.db.NewInsert().Model(botEndpoint).Exec(repo.ctx)
	if err != nil {
		return err
	}

	log.Println("inserted bot endpoint id: ", botEndpoint.Id)

	return nil
```

2024-01-25 15:45 UTC, kei01234kei commented on usecase/usecase.go
> +		}
全ての `return err` 部分に言えることだけど、ただ単に `err` を返すだけじゃなくて、背景情報もエラーに含めてあげるとデバッグがしやすくなるよ

```go
// if err != nil {
// 	return err
// }

if err != nil {
 	return xerros.Errorf("サーバーの登録に失敗しました。server -> %+v: %+v", server, err)
}
```

2024-01-25 15:50 UTC, kei01234kei commented on db/setup_db.go
> +)
import は`標準パッケージ`、`ダウンロードしてきたパッケージ`、`現在のモジュール内のパッケージ` ごとに1行あけるようにしよう！

```go
import (
	"context"
	"database/sql"
	"log"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/extra/bundebug"

	"github.com/hebitigo/CATechAccelChatApp/entity"
)
```

2024-01-25 15:51 UTC, kei01234kei requested changes
コメントをつけたところを直せるとよさそう！
努力してるの伝わってきた素晴らしい PR だね！

2024-01-26 07:06 UTC, hebitigo commented
指摘頂いた内容を修正しました。
errorに関してはstac traceをつけるために[github.com/cockroachdb/errors](https://github.com/cockroachdb/errors)を使いました。

参考
[次なる`pkg/errors`を探して](https://tech.kanmu.co.jp/entry/2023/06/19/150000)](https://tech.kanmu.co.jp/entry/2023/06/19/150000)

2024-01-27 12:37 UTC, kei01234kei approved these changes
![68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f323236333432](https://github.com/hebitigo/CATechAccelChatApp/assets/62370522/9963a18d-7308-45f9-8b4a-681b671b82c5)

2024-01-27 12:38 UTC, merged

2024-01-27 12:38 UTC, kei01234kei commented
![68747470733a2f2f696d6167652e6c67746d6f6f6e2e6465762f323334383631](https://github.com/hebitigo/CATechAccelChatApp/assets/62370522/dcf49f52-b351-4d8f-8294-59a860735364)